package com.nareshtech.jsontypicode_retrofit.data

// DTO for Response of GET request , Posts and POST /posts
data class PostDto(
    val userID:Int,
    val id:Int? = null, // ID is generated by the server for new Posts, so it can be null on request.
    val title:String,
    val body: String
)
